### ISSUE TITLE
汎用ダイアログの作成

### ISSUE THREAD

**Issue by nagatea** [traPtitech/booQ#100]
タイトルと中身を表示してOKまたは外枠をクリックすると閉じれるようなダイアログをコンポーネント化する

**Comment by ryoha000** [comment]
急ぎじゃないらしいですしコンポーネントに切り出せなかったので止めます
v-overlayを参考にしたらいいと思います

**Comment by nagatea** [comment]
いまalertなのをいい感じに自前実装したいね(かっこいいので)
