### ISSUE TITLE
LogsからLatestLogsを生成するロジック

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/booQ#129]
急ぎではないですが明らかなパフォーマンス改善につながります

**Comment by ryoha000** [comment]
Vue(JS)でお願いします

**Comment by nagatea** [comment]
やるなら鯖側のほうが良さそう
Goのほうが処理速度早いし型が付いてるので実装もしやすい
テストが書けるのもでかい

明らかにやるのは今ではないけど
