### ISSUE TITLE
開発環境のDBの文字化け修正

### ISSUE THREAD

**Issue by nagatea** [traPtitech/booQ#139]
おそらくビルド時に使ってるMariaDBコンテナの設定をいじらないといけない気がする
使ってる文字コードが`utfmb4`なのでそれに合わせないといけない？

**Comment by nagatea** [comment]
これdocker側では適切に実行されてるっぽい
たぶんmysqlに入る時のコマンドで文字コードを指定して入らないといけないっぽい

**Comment by ryoha000** [comment]
問題なさそうなのでとりあえず閉じます
