### ISSUE TITLE
ダッシュボードをいい感じに

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/booQ#164]
今のところ諸々がおざなり
vuetifyにcalendarっていう機能があってそこに借りてる物品の返却予定日を備品とそれ以外で色分けして小さな丸で表示する
その丸をクリックかホバーするとその物品の詳細がにゅっと表示される
そこからまとめて返すためのまとめるボタンをつける
そしてcalendarの下に、まとめて返却できるitemの名前と数を表示して、その下(buttom)か上にまとめて返すボタンの実装。
あと返却予定日をすぎてたら警告文が出るようにする
まとめて返せるのは備品か支援課のもの(itemのtypeが0じゃないもの)

**Comment by nagatea** [comment]
ちょっとタスクがでかいので切り分けようか
* 返却カレンダー機能の追加
* カレンダーから返却できるようにする
* 返却予定日をすぎてたらダッシュボードに警告が出るようにする

追加はryohaくんにお願いします(終わったらこのissueをcloseしておいて)
