### ISSUE TITLE
Item削除の権限周り

### ISSUE THREAD

**Issue by nagatea** [traPtitech/booQ#177]
仕様的には管理者しか備品は消せない
今確認したらリクエストが来たら誰でも消せるようになっててやばい

備品かつ管理者だったときに消せるようにする
クライアント側も備品で管理者じゃなかったらボタンが表示されないようにする

**Comment by ryoha000** [comment]
PutItemを実装してからでないとまずい
先にそっちのissueをやってください

**Comment by nagatea** [comment]
クライアント側は別タスクたてます
