### ISSUE TITLE
スマホ版ItemListのタイトルのフォントサイズを小さくする

### ISSUE THREAD

**Issue by nagatea** [traPtitech/booQ#179]
タイトル通りです
現状ほとんどの名前が見切れてしまっている
![1969AD80-175F-44F6-9E47-2A3CE591EC6B](https://user-images.githubusercontent.com/24384201/66687080-7a37e100-ecbc-11e9-9572-16afd356ad0f.jpeg)

**Comment by sapphi-red** [comment]
booQ UIで:kan:
