### ISSUE TITLE
カレンダー機能のXSS脆弱性

### ISSUE THREAD

**Issue by nagatea** [traPtitech/booQ#210]
カレンダーのタイトルに任意スクリプトが埋め込めることが発覚

![image](https://user-images.githubusercontent.com/24384201/66982131-81158800-f0f0-11e9-97b5-f78643007ce7.png)

直接のスクリプト実行はされないようだが、htmlタグが普通に解釈されるっぽいのでhtmlでイベントを指定するとスクリプトが発火する
カレンダーはVuetify側でレンダリングしてるのでVuetifyの問題
サンプルコードの時点で任意実行できることを確認

どうしようね

**Comment by tohutohu** [comment]
ここ
[vuetify/events.vue at 2012fb443a168ae2a221051b6ff885c88fdb6317 · vuetifyjs/vuetify](https://github.com/vuetifyjs/vuetify/blob/2012fb443a168ae2a221051b6ff885c88fdb6317/packages/docs/src/examples/calendars/complex/events.vue#L78)

**Comment by nagatea** [comment]
いや、そこではない
そこは詳細タブの描画なのでカレンダーの表示とはちがう
![image](https://user-images.githubusercontent.com/24384201/66983600-def79f00-f0f3-11e9-9360-55a49b2a57fa.png)

ちなみにそこはレビュー段階で潰した
https://github.com/traPtitech/booQ/pull/201#discussion_r334773383

**Comment by tohutohu** [comment]
すまんもうちょっとちゃんとコードリーディングした
ここでちゃんとサニタイジングしないといけないっぽいのかな？

普通にPRだしたら喜ばれそう
[vuetify/calendar-with-events.ts at f0ec7dba89da409bb647f1a947159126f9838acb · vuetifyjs/vuetify](https://github.com/vuetifyjs/vuetify/blob/f0ec7dba89/packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts#L99)

**Comment by nagatea** [comment]
同じところみてて笑った
vuetify側がサニタイズ関数持ってると楽なんですけどね

**Comment by nagatea** [comment]
あったわ
https://github.com/vuetifyjs/vuetify/blob/9a3ce0b9ab6698ff777e5d43bbefb5e789920ca8/packages/vuetify/src/util/helpers.ts#L270

**Comment by tohutohu** [comment]
もしくはここをもう少しちゃんと開いてやるか
[vuetify/calendar-with-events.ts at f0ec7dba89da409bb647f1a947159126f9838acb · vuetifyjs/vuetify](https://github.com/vuetifyjs/vuetify/blob/f0ec7dba89/packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts#L282)

**Comment by tohutohu** [comment]
↑じゃあPR出せるやん
頑張れ
