### ISSUE TITLE
本番環境の自動デプロイ

### ISSUE THREAD

**Issue by nagatea** [traPtitech/booQ#257]
* ビルドしたイメージをDockerHubにあげる
* `deploy.sh`を作り、以下の手順でコンテナを入れ替える
  * docker-compose stop
  * docker pull
  * docker-compose up
* CircleCIにそれを実行する設定を書く
  * ビルドしてpushするところも自動でできるようにしてえ
* Ansibleを実行しても最小限のことしかしないように修正する

**Comment by sapphi-red** [comment]
devopsで実現した
