### ISSUE TITLE
画像アップロード時に透明な部分が黒くなる

### ISSUE THREAD

**Issue by nagatea** [traPtitech/booQ#269]
![image](https://user-images.githubusercontent.com/24384201/69815459-b78b0a80-1239-11ea-92d3-98274f8ea84b.png)

まあ背景が透明な画像がアップロードされることは実用上は無いので後回しでも大丈夫

(せめて白がいいな...)

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/booQ/blob/f520373e37a6bea22d229b421f9e92bef312492c/router/files.go#L44-L56
https://www.socketloop.com/tutorials/golang-convert-png-transparent-background-image-to-jpg-or-jpeg-image
