### ISSUE TITLE
validatorを使う

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/booQ#283]
これとか

https://github.com/go-ozzo/ozzo-validation

ハンドラー内でいちいち書かないようにしたい

**Comment by H1rono** [comment]
[go-ozzo/ozzo-validation](https://github.com/go-ozzo/ozzo-validation)で、↓のような手順で実装しようと考えています。

1. modelの各構造体`T`に対して`func (t T) Validate() error`を実装する
2. 各ハンドラ`func handler(c echo.Context) error`内で`c.Validate(t)`を呼び出してバリデーションを施す

参考: [Go の入力バリデーションパッケージ ozzo-validation を試した。](https://zenn.dev/mattn/articles/893f28eff96129) ([mattn/go-ozzo-validation-example](https://github.com/mattn/go-ozzo-validation-example))

@ryoha000 良さそうと思ったら :+1: をお願いします。

**Comment by ryoha000** [comment]
@H1rono 
返信遅くてごめんなさい:pray:
それでいいと思います:+1:

**Comment by H1rono** [comment]
↓は各エンドポイントに対してバリデーションが必要と思われる構造体の型です。

エンドポイント | 構造体
:-- | :--
`POST /items/:id/comments` | `User`?,`RequestPostCommentBody`
`GET /comments` |
`POST /files` | `User`?
`GET /files/:id` |
`GET /items` | `User`?
`POST /items` | `User`?, `Item`
`GET /items/:id` |
`PUT /items/:id` | `User`?, `map[string]interface`(`Item`)
`DELETE /items/:id` | `User`?
`POST /items/:id/owners` | `User`?, `RequestPostOwnersBody`
`PUT /items/:id/owners` | `User`?, `RequestPostOwnersBody`
`POST /items/:id/likes` | `User`?
`DELETE /items/:id/likes` | `User`?
`POST /items/:id/logs` | `User`?, `RequestPostLogsBody`
`GET /users/me` | `User`?
`GET /users` |
`PUT /users` | `RequestPutUsersBody`, `User`?

リクエストから直接抽出している構造体のみを列挙しました。`User`? となっているのは`c echo.Context`に対して`c.Get("user").(model.User)`として構造体を抽出しており、これはバリデーションすべきかどうかわからなかったためです。

@ryoha000 これらの構造体に対して、具体的にどのようなバリデーションを施したらいいでしょうか?

**Comment by ryoha000** [comment]
返信遅くなってごめんなさい
ちゃんとまとめてるのいいですね:+1:

> c echo.Contextに対してc.Get("user").(model.User)として構造体を抽出

これは https://github.com/traPtitech/booQ/blob/680849660a740c300db54eed5e966145a19ff082/router/middleware.go#L41 でセットしたものを読んでるだけなので validation の必要はないです

> これらの構造体に対して、具体的にどのようなバリデーションを施したらいいでしょうか?

urlが入るべきなところは`validate:"url"`みたいに書いて validation するみたいな感じですかね
あと最大/最小文字数とか
`PUT /items/:id`が`map`で値をもらってるのはよくわからないんですが普通に構造体定義しなおしてもらって大丈夫です:+1:

**Comment by H1rono** [comment]
@ryoha000 

https://github.com/traPtitech/booQ/blob/680849660a740c300db54eed5e966145a19ff082/docs/schema.md?plain=1#L3-L9

`code`の物品管理コードとはなんでしょうか?(何かルールに基づいて決められているものでしょうか?)

あと、`type`の説明がソースコード↓と明らかに違うのですが、どちらが正しいのでしょうか?

https://github.com/traPtitech/booQ/blob/680849660a740c300db54eed5e966145a19ff082/router/items.go#L71

**Comment by ryoha000** [comment]
物品管理コードは今のところ設定されてないけどtraPで物品をバーコードとかで管理したくなったらつけるようなやつ

`type`はソースコードがただしいです

**Comment by H1rono** [comment]
テストケースの↓のみコードが12桁で他は全て13桁なのですが、これはテストケースが誤りということでしょうか?

https://github.com/traPtitech/booQ/blob/680849660a740c300db54eed5e966145a19ff082/router/items_test.go#L406-L412

**Comment by ryoha000** [comment]
それはテストケースがなぜか一文字削除されて12桁になってそう
ただ前述のとおりオリジナルの物品コードにも使いそうだから13桁決め打ちとかはしたくないかも
