### ISSUE TITLE
ポップアップが小さすぎる

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/booQ#348]

**Comment by ryoha000** [comment]
参考
![image](https://user-images.githubusercontent.com/48485650/83014700-223ac880-a05a-11ea-8161-1f11902cd14f.png)

**Comment by Rozelin-dc** [comment]
Rozelinです
QSoCでやりたいです

**Comment by ryoha000** [comment]
このダイアログはしたのファイルで作られてるコンポーネントです
https://github.com/traPtitech/booQ/blob/master/client/src/components/shared/CommentDialog.vue

このダイアログのサイズはこの行の`max-width`とかで指定してます
https://github.com/traPtitech/booQ/blob/da36b2c1e3b475b466fbf7d5d2a816e70c060c36/client/src/components/shared/CommentDialog.vue#L7

今はこれをpixel数で指定していますが%で指定するようにしたい、というのがこのissueです

このv-dialogというタグのコンポーネントはこのURLをみたらわかるかもしれません
https://vuetifyjs.com/ja/components/dialogs/
