### ISSUE TITLE
いいねのアイコンが密じゃ無さ過ぎ

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/booQ#349]

**Comment by ryoha000** [comment]
参考
![image](https://user-images.githubusercontent.com/48485650/83014783-44344b00-a05a-11ea-85fa-dc247ee19bda.png)

**Comment by sapphi-red** [comment]
keep social distance

**Comment by ryoha000** [comment]
ﾜﾛﾀw

**Comment by ntaso2051** [comment]
traPID Nです！QSoCでやってみたいです！
