### ISSUE TITLE
本番用DockerfileでGolangのイメージにNodejsを入れている

### ISSUE THREAD

**Issue by mazrean** [traPtitech/booQ#373]
マルチステージビルドを有効活用しましょう。

**Comment by sapphi-red** [comment]
これ入ってないと思うけど別の箇所見てない？

**Comment by mazrean** [comment]
ここで入れているけど、このDockerfileって本番用じゃないの？
https://github.com/traPtitech/booQ/blob/master/docker/production/Dockerfile#L2

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/booQ/blob/86c91e83f0683126df004acd03677e41fb35b2e7/docker/production/Dockerfile#L15
ここでマルチステージビルドになってない？

**Comment by mazrean** [comment]
イメージの大きさは変わらないけど、Node.jsを入れる分ビルド時間とビルドに使うリソースが増えるので、golangのイメージへNode.jsを入れるよりは、Node.jsのイメージでクライアントのビルドをしたほうがきれいじゃない？
あと、いつかBuildKitに対応している環境ではビルド時間が圧倒的に早くなるというのもメリット。（最初のコメントはあくまでも「有効活用」で、やっている・いないの話のつもりではない）

**Comment by sapphi-red** [comment]
イメージサイズじゃなくてビルド時間の話してたのね
確かに多少早くはなりそう
