### ISSUE TITLE
swaggerの改善

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/booQ#413]
- [x] paramsのrequiredの付与 (参考: https://github.com/traPtitech/traQ/pull/690)
- [x] enumの利用 (参考: https://github.com/traPtitech/traQ/pull/674, https://github.com/traPtitech/traQ/pull/842)
- [x] リクエスト/レスポンスのrequiredの付与 (参考: https://github.com/traPtitech/traQ/pull/819)
- [x] リクエスト/レスポンスのnullableの付与 (参考: https://github.com/traPtitech/traQ/pull/819)

**Comment by ryoha000** [comment]
```
match itemType {
  0 => 個人のやつ,
  1 => 備品,
  2 => 支援課のやつ,
}
```
```
match logType {
  0 => 借りる,
  1 => 返却,
}
```
