### ISSUE TITLE
`imgUrl`はoptional？

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/booQ#493]
@ryoha000 これ実はoptionalだったりする？
https://github.com/traPtitech/booQ/blob/72325704be3960404925774e0e7ca74807b7988e/docs/swagger.yml#L687

**Comment by ryoha000** [comment]
初期のものは入ってなくてある時期境に""にした気がする

**Comment by ryoha000** [comment]
↑これは勘違いだった
どれ見て思ったの？

**Comment by sapphi-red** [comment]
あ～optionalじゃなくて`''`はそう
それはそうになった

**Comment by ryoha000** [comment]
TODO: swaggerに空文字列なの明記する!!
