### ISSUE TITLE
所有数が0個になった時、表示しないようにする

### ISSUE THREAD

**Issue by logica0419** [traPtitech/booQ#508]
![image](https://user-images.githubusercontent.com/84759675/136652553-a5e6967b-f684-4fad-9b3c-a5aad5fd363c.png)
物品を減らすことができるのでこういうことが起こりうる、物理的に有効な数が登録されていない物品が表示されているのはUX的にちょっとうっとおしい
所有者が提供できる物品数を減らした際、

- その人が持っている個数が0なら所有者欄に表示しない
- 合計物品数が0ならアイテム欄に表示しない

という挙動が欲しい
DBからの項目削除でいいのではと思ったのでバックエンド側のissueとしたが、イベント履歴などいくつかの項目を残しておきたい場合は追加で「available」みたいなフィールド付けるかクライアント側で有効な品物かの判断を行うみたいな感じになると思うのでフロントエンドでも改修が必要かも。仕様の検討が必要。

**Comment by ryoha000** [comment]
フロントで見えなくするのはいいと思うんですがバックエンドでなんかする必要はないかなって思ってます(`available`みたいなものをつけたいモチベーションがわからない)

**Comment by logica0419** [comment]
物理的に供給不可能な物資なので、自分の中ではこの0と1以上の扱いの差が大きいため、あるものと無いものが同様に扱われてAPIを叩いたときにどちらのデータも帰ってくるのが個人的に気持ち悪いだけですね…
まあそこはりょはさんの判断に任せた方がいいと思うので、フロントで表示するかを切り替える方向でいいかもしれません

**Comment by ryoha000** [comment]
これはフロントでやる
